added submodules

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,9 +5,6 @@ on:
     branches:
       - main
       - feat/ci_juno
-  # pull_request:
-  #   branches:
-  #     - main
 
 jobs:
   build-and-test:
@@ -22,28 +19,35 @@ jobs:
         uses: actions/setup-go@v4
         with:
           go-version: 1.23.1
-      
+
+      # - name: Debug Repository Contents
+      #   run: |
+      #     echo "Listing repository contents..."
+      #     ls -al
+      #     echo "Checking Juno directory..."
+      #     ls -al juno || echo "Juno directory is missing!"
+
       - name: Check Code Formatting
         run: |
           echo "Checking formatting with go fmt..."
           go fmt ./... || exit 1
           echo "Formatting checked successfully!"
 
-      # - name: Install Dependency
-      #   run: |
-      #     go mod tidy
+      # - name: Install jemalloc
+        # run: |
+        #   sudo apt-get update
+        #   sudo apt-get install -y libjemalloc-dev
 
-      - name: Install jemalloc
+      - name: Fetch Juno Submodule
         run: |
-          sudo apt-get update
-          sudo apt-get install -y libjemalloc-dev
+          echo "Initializing Juno submodule..."
+          git submodule update --init --recursive
 
       - name: Build Juno
         run: |
           echo "Building Juno..."
           cd juno
           make juno
-          cd ..
 
       - name: Build Plugin
         run: |
