modified ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,57 +1,63 @@
 name: Juno Plugin CI
 
+# Trigger the workflow on push events specifically for the 'master' branch
 on:
-    push:
-      branches:
-        # - master
-        - feat/ci_plugin
-  
-  jobs:
-    build:
-      # Set the job name and specify it runs on the latest Ubuntu virtual environment
-      name: Building CI pipeline on Ubuntu OS
-      runs-on: ubuntu-latest
-  
-      steps:
-        # Step to check out the code from the Git repository so that it can be used in subsequent steps
-        - name: Checkout code
-          uses: actions/checkout@v2
-  
-        # Step to update any Git submodules recursively, ensuring that any dependent repositories are also up to date
-        - name: Update submodules
-          run: git submodule update --init --recursive
+  push:
+    branches:
+      - feat/ci_plugin
 
-        - name: Set Up Go
-            uses: actions/setup-go@v4
-            with:
-            go-version: 1.23.1
+jobs:
+  build:
+    # Set the job name and specify it runs on the latest Ubuntu virtual environment
+    name: Building CI pipeline on Ubuntu OS
+    runs-on: ubuntu-latest
 
-        # - name: Install jemalloc
-        #   run: |
-        #     sudo apt-get update
-        #     sudo apt-get install -y libjemalloc-dev
+    steps:
+      # Step to check out the code from the Git repository so that it can be used in subsequent steps
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-        - name: Check Code Formatting
-            run: |
-            echo "Checking formatting with go fmt..."
-            go fmt ./... || exit 1
-            echo "Formatting checked successfully!"
-        - name: Build Juno
-            run: |
-            echo "Building Juno..."
-            cd juno
-            make juno
+      # Step to update any Git submodules recursively, ensuring that any dependent repositories are also up to date
+      - name: Update submodules
+        run: git submodule update --init --recursive
 
-        # - name: Build Plugin
-        #   run: |
-        #     echo "Building Juno Plugin..."
-        #     make build
-        #     ls -al build
+      # Step to set up Go
+      - name: Set Up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: 1.23.1
 
-        # - name: Validate Plugin Build
-        #   run: |
-        #     echo "Validating the plugin .so file..."
-        #     if [ ! -f "./build/myplugin.so" ]; then
-        #       echo "Error: Plugin .so file not found!"
-        #       exit 1
-        #     fi
+      # Uncomment this section if jemalloc is required
+      # - name: Install jemalloc
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y libjemalloc-dev
+
+      # Step to check code formatting
+      - name: Check Code Formatting
+        run: |
+          echo "Checking formatting with go fmt..."
+          go fmt ./... || exit 1
+          echo "Formatting checked successfully!"
+
+      # Step to build Juno
+      - name: Build Juno
+        run: |
+          echo "Building Juno..."
+          cd juno
+          make juno
+
+      # Uncomment this section to build the plugin
+      # - name: Build Plugin
+      #   run: |
+      #     echo "Building Juno Plugin..."
+      #     make build
+      #     ls -al build
+
+      # Uncomment this section to validate the plugin build
+      # - name: Validate Plugin Build
+      #   run: |
+      #     echo "Validating the plugin .so file..."
+      #     if [ ! -f "./build/myplugin.so" ]; then
+      #       echo "Error: Plugin .so file not found!"
+      #       exit 1
