Modified deploy_pitchlake_indexer.yaml file

diff --git a/.github/workflows/deploy_pitchlake_indexer.yaml b/.github/workflows/deploy_pitchlake_indexer.yaml
--- a/.github/workflows/deploy_pitchlake_indexer.yaml
+++ b/.github/workflows/deploy_pitchlake_indexer.yaml
@@ -9,8 +9,8 @@ env:
     AWS_REGION: eu-central-1
     ECR_REPOSITORY: pitchlake-ui-new_images_repository
     EC2_SERVICE: pitchlake-indexer-instance
-    EC2_HOST: 18.196.81.140
-    EC2_USER: ubuntu
+    EC2_HOST: ${{ secrets.EC2_HOST }}
+    EC2_USER: ${{ secrets.EC2_USER }}
     PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
     APP_PORT: 6060
 
@@ -59,85 +59,79 @@ jobs:
           echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
           docker buildx build --platform=linux/amd64 -f ./Dockerfile -t $IMAGE_URI ./
           docker push $IMAGE_URI
-    
-      # - name: Pull Docker image
-      #   run: |
-      #     docker pull $IMAGE_URI
       
       # EC2 Deployment Steps
-      - name: SSH into EC2
+      - name: Change key permission
         run: |
           echo "$PRIVATE_KEY" > private_key
           chmod 600 private_key
       
-      - name: Login to AWS ECR on EC2 instance
+      - name: Deploy Docker Image on EC2 instance
         env:
             AWS_REGION: ${{ env.AWS_REGION }}
             ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        run: |
-          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
-            aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin ${ECR_REGISTRY}
-            "
+            IMAGE_TAG: ${{ env.IMAGE_TAG }}
+            ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
+        uses: appleboy/ssh-action@v0.1.6
+        with: 
+          host: ${{ env.EC2_HOST }}
+          username: ${{ env.EC2_USER }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if ! command -v docker &> /dev/null; then
+              sudo apt update
+              sudo apt install -y docker.io
+            fi
 
-      - name: Pull Docker image on EC2 instance
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
-            IMAGE_URI=\"${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"
-            sudo docker pull $IMAGE_URI
-          "
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
+      #       aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin ${ECR_REGISTRY}
+      #       "
 
-      - name: Clean up existing containers and images on EC2
-        run: |
-          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
-            sudo docker ps -aq | xargs -r sudo docker rm -f || true
-            sudo docker images -aq | xargs -r sudo docker rmi -f || true
-           "
+      # - name: Pull Docker image on EC2 instance
+      #   env:
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
+      #     IMAGE_TAG: ${{ github.sha }}
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
+      #       IMAGE_URI=\"${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"
+      #       sudo docker pull $IMAGE_URI
+      #     "
+
+      # - name: Clean up existing containers and images on EC2
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
+      #       sudo docker ps -aq | xargs -r sudo docker rm -f || true
+      #       sudo docker images -aq | xargs -r sudo docker rmi -f || true
+      #      "
   
-      - name: Run Docker container on EC2
-        env:
-          APP_PORT: ${{ env.APP_PORT }}
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
-          IMAGE_TAG: ${{ github.sha }}
-          DOCKER_CONTAINER: ${{env.DOCKER_CONTAINER}}
-        run: |
-          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
-            IMAGE_URI=\"${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"
-            sudo docker run --env-file .env -d --name $DOCKER_CONTAINER -p ${APP_PORT}:${APP_PORT} $IMAGE_URI
-          "
+      # - name: Run Docker container on EC2
+      #   env:
+      #     APP_PORT: ${{ env.APP_PORT }}
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
+      #     IMAGE_TAG: ${{ github.sha }}
+      #     DOCKER_CONTAINER: ${{env.DOCKER_CONTAINER}}
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
+      #       IMAGE_URI=\"${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"
+      #       sudo docker run --env-file .env -d --name $DOCKER_CONTAINER -p ${APP_PORT}:${APP_PORT} $IMAGE_URI
+      #     "
 
-      - name: Logout from AWS ECR on EC2
-        env:
-          AWS_REGION: ${{ env.AWS_REGION }}
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        run: |
-          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
-            aws ecr get-login-password --region ${AWS_REGION} | sudo docker logout ${ECR_REGISTRY}
-          "
+      # - name: Logout from AWS ECR on EC2
+      #   env:
+      #     AWS_REGION: ${{ env.AWS_REGION }}
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #   run: |
+      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
+      #       aws ecr get-login-password --region ${AWS_REGION} | sudo docker logout ${ECR_REGISTRY}
+      #     "
 
 
-        # uses: appleboy/ssh-action@v0.1.6
-        # with: 
-        #   host: ${{ env.EC2_HOST }}
-        #   username: ${{ env.EC2_USER }}
-        #   key: ${{ secrets.EC2_SSH_KEY }}
 
-        #   script: |
-        #   # Install Docker if not already installed
-        #   if ! command -v docker &> /dev/null; then
-        #     sudo apt update
-        #     sudo apt install -y docker.io
-        #   fi
-          
-        #   # Install Docker Compose if not already installed
-        #   if ! command -v docker-compose &> /dev/null; then
-        #     sudo curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-        #     sudo chmod +x /usr/local/bin/docker-compose
-        #   fi
+
+
         #     IMAGE_URI=${{ secrets.ECR_IMAGE_URI }}
         #     echo "Deploying Docker image: $IMAGE_URI"
         #     docker pull $IMAGE_URI
